# Generated by Django 4.0.6 on 2022-07-15 21:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auth', '0003_alter_useractivationrequestmodel_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivationRequestModel',
            new_name='AccountActivationRequestModel',
        ),
    ]
