# Generated by Django 4.0.6 on 2022-07-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_rename_useractivationrequestmodel_accountactivationrequestmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountActivationRequestModel',
        ),
    ]
