# Generated by Django 4.0.6 on 2022-07-18 23:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarData', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritecarsmodel',
            unique_together={('car_type', 'user')},
        ),
    ]
