# Generated by Django 4.0.6 on 2022-07-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartypesmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturernamesmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
