# Generated by Django 4.0.6 on 2022-07-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0003_alter_favouritecarsmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartypesmodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
