# Generated by Django 4.0.6 on 2022-07-20 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0004_alter_cartypesmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecarsmodel',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1880), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
