# Generated by Django 4.0.6 on 2022-07-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0005_alter_favouritecarsmodel_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartypesmodel',
            unique_together={('manufacturer', 'name')},
        ),
    ]
