# Generated by Django 4.0.6 on 2022-07-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0006_alter_cartypesmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecarsmodel',
            name='fuel',
            field=models.CharField(choices=[('Gas', 'Gas'), ('Diesel', 'Diesel'), ('LPG gas', 'LPG gas'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
    ]
