# Generated by Django 4.0.6 on 2022-07-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarNewManufacturerRequest',
            new_name='CarNewManufacturerRequestsModel',
        ),
    ]
