# Generated by Django 4.0.6 on 2022-07-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarData', '0007_alter_favouritecarsmodel_fuel'),
        ('AdminSite', '0002_rename_carnewmanufacturerrequest_carnewmanufacturerrequestsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarNewManufacturerRequestsDeleteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarData.manufacturernamesmodel')),
            ],
        ),
    ]
