# Generated by Django 4.0.6 on 2022-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_accountdeleterequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requested_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AccountDeleteRequestModel',
        ),
    ]
